name: publish

on:
  push:
    tags:
    - '*'

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Hatch
        run: |
          python -m pip install -U hatch
      - name: Build package
        run: |
          hatch build
      - name: Publish
        run: |
          hatch publish
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_API_TOKEN }}